name: CI
env:
  MACOSX_DEPLOYMENT_TARGET: "15.4"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: SwiftyLab/setup-swift@v1
      with:
        swift-version: "6.3"
        
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v --enable-code-coverage
      
    - name: Upload
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_SHUWANG1_LIBGNSS_GPS_SIM_TOKEN }}
